const data = {
  products: [
    {
      name: 'Tp-Link Router',
      slug: 'tplink-router',
      category: 'Router',
      image: '/images/router.jpg',
      price: 1,
      brand: 'Tp-Link',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'TP-Link TL-WR840N 300Mbps Wireless N Router',
    },
    {
      name: 'Air Wick',
      slug: 'air-wick',
      category: 'Pants',
      image: '/images/airwick.jpg',
      price: 75,
      brand: 'Querra',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Air Wick 2-Piece Freshmatic Start Kit 250ml',
    },

    {
      name: 'Samsung TV',
      slug: 'samsung-tv',
      category: 'Electronics',
      image: '/images/tv.jpg',
      price: 1,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Samsung 43 Inches 4K UHD LED Smart TV Black',
    },
    {
      name: 'Monitor',
      slug: 'monitor',
      category: 'electronics',
      image: '/images/monitor.jpg',
      price: 1,
      brand: 'LG',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "'32'' Class Full HD IPS LED Monitor (31.5'' Diagonal)'",
    },
    {
      name: 'Xbox Wireless Controller',
      slug: 'Xbox-wireless-controller',
      category: 'controllers',
      image: '/images/xbox.jpg',
      price: 1,
      brand: 'Xbox',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Textured triggers and bumpers I Hybrid D-pad I Button mapping I Bluetooth® technology',
    },

    {
      name: 'Dell Laptop',
      slug: 'dell-laptop',
      category: 'Laptop',
      image: '/images/laptop.jpg',
      price: 1,
      brand: 'Dell',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Laptop Dell Latitude E7240 4GB Intel Core I5 SSD 128GB',
    },

  ],
};

export default data;